# Generated by Django 5.0.6 on 2024-05-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50)),
                ('message_us', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pic')),
                ('venue', models.CharField(default='Venue ', max_length=200)),
                ('location', models.CharField(default='Location currently unavailable', max_length=200)),
                ('eve_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('eve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.event')),
            ],
        ),
    ]
